#!/bin/bash
#
echo "GIT"
cat > ~/.gitconfig << EOF
; autogenerated by auto-setup/git/setup.sh
[user]
  name = Falk Schoenfeld
  email = falk.fairfield@gmail.com
[include]
  path = ~/auto-setup/git/gitconfig
EOF

# ln -s ~/auto-setup/git/gitconfig ~/.gitconfig
# cp ~/auto-setup/git/gitlocalenv.sh
${EDITOR:=nvim} -O "$HOME/.gitconfig" "$HOME/auto-setup/git/gitlocalenv.sh"
