#!/bin/bash

# script to autogenerate parallel workspaces for all monitors
# should be called by i3 config

source ~/auto-setup/sway/ws_config.sh

if [ -z $SWAYSOCK ]; then
    WM_MSG=i3-msg
else
    WM_MSG=swaymsg
fi

OUT="$HOME/.config/i3/i3-multihead.config"

WS_NAMES=$1
# for testing
# MON_NAMES=( $2 )
# MON_NUM=3
MON_NUM=$(. ~/auto-setup/x/count_monitors.sh)
MON_NAMES=( $(. ~/auto-setup/x/get_monitor_names.sh) )

rm -rf $OUT
echo "# AUTOGENERATED BY ~/auto-setup/i3/generate_multihead_setup.sh" > $OUT
echo "workspace_auto_back_and_forth no" >> $OUT

echo "" >> $OUT
for WS_NAME in $WS_NAMES
do
    # set up commands for control
    # assumes single character ws names [0-9a-z] as it sets them as the access key as well 
    # TODO more control via menu which allows sending to specific screens?
    echo "bindsym \$mod+$WS_NAME exec \$cmd_switch_multihead $WS_NAME" >> $OUT
    echo "bindsym \$mod+shift+$WS_NAME exec \$cmd_move_multihead $WS_NAME" >> $OUT
    for (( WS_C=1; WS_C<=$MON_NUM; WS_C++ ))
    do
        let I=$WS_C-1
        echo "workspace $WS_NAME$SEPARATOR$WS_C output ${MON_NAMES[$I]}" >> $OUT
    done
    echo "" >> $OUT
done
echo "exec_always \$cmd_switch_multihead 1" >> $OUT
