#!/bin/bash
source ~/auto-setup/bash/env_variables.sh
source $FAUTOSETUP/bash/general.sh

# ${debian_chroot:+($debian_chroot)}\u@\h:\w\$ 

export PS1="\[\033[1m\]\h:\u:\w \[\033[0m\]"


if [ -d /home/$USER/bin ]; then
    PATH+="$PATH:/home/$USER/bin"
fi
if [ -d /home/$USER/.local/bin ]; then
    PATH+="$PATH:/home/$USER/.local/bin"
fi

source $FAUTOSETUP/bash/editors.sh

# General
alias ali="$EDITOR $FAUTOSETUP/bash/bashrc; bash"
# each workplace will have their own stuff, so drop that in here
alias alii="$EDITOR ~/.bash_individual_aliases; bash"

# sources all files if they exist
if [ -d ~/.bash_individual_aliases ]; then
for file in ~/.bash_individual_aliases/*; do
  if [ -f "$file" ] ; then
    . "$file"
  fi
done
fi

# if [ -f ~/.bash_individual_aliases ]; then
#     . ~/.bash_individual_aliases
# fi

source $FAUTOSETUP/bash/tmux.sh
source $FAUTOSETUP/bash/git.sh
source $FAUTOSETUP/bash/jvm.sh

# history - ignore duplicates
export HISTCONTROL=ignoredups

# jupyter
# alias jnc="jupyter nbconvert --to script"

source $FAUTOSETUP/bash/convenience.sh

source $FAUTOSETUP/bash/ranger.sh
source $FAUTOSETUP/bash/feh.sh
source $FAUTOSETUP/bash/vnc.sh


source $FAUTOSETUP/bash/x.sh
source $FAUTOSETUP/bash/serial.sh


# wms
source $FAUTOSETUP/bash/wsl.sh
if [ -f /bin/i3 ]; then
    alias i3c="$EDITOR ~/.config/i3/config"
fi

# if [ -f /bin/docker ]; then
#   source $FAUTOSETUP/docker/aliases_docker.sh
# fi

# source $FAUTOSETUP/bash/aliases_sway.sh
# source $FAUTOSETUP/bash/aliases_regolith.sh

# distrostuff based on lsb_release
source $FAUTOSETUP/bash/distrostuff.sh

source $FAUTOSETUP/bash/colors.sh



