#!/bin/bash
source ~/auto-setup/bash/env_variables.sh
source $FAUTOSETUP/bash/general.sh

# ${debian_chroot:+($debian_chroot)}\u@\h:\w\$ 

export PS1="\[\033[1m\]\u:\w \[\033[0m\]"


if [ -d /home/$USER/bin ]; then
    PATH+="$PATH:/home/$USER/bin"
fi
if [ -d /home/$USER/.local/bin ]; then
    PATH+="$PATH:/home/$USER/.local/bin"
fi

source $FAUTOSETUP/bash/editors.sh

# General
alias ali="$EDITOR $FAUTOSETUP/bash/bashrc; bash"
# each workplace will have their own stuff, so drop that in here
alias alii="$EDITOR ~/.bash_individual_aliases; bash"

# sources all files if they exist
if [ -d ~/.bash_individual_aliases ]; then
for file in ~/.bash_individual_aliases/*; do
  if [ -f "$file" ] ; then
    . "$file"
  fi
done
fi

# if [ -f ~/.bash_individual_aliases ]; then
#     . ~/.bash_individual_aliases
# fi

source $FAUTOSETUP/bash/tmux.sh
source $FAUTOSETUP/bash/git.sh
source $FAUTOSETUP/bash/jvm.sh

# history - ignore duplicates
export HISTCONTROL=ignoredups

# jupyter
# alias jnc="jupyter nbconvert --to script"

source $FAUTOSETUP/bash/aliases_convenience.sh

source $FAUTOSETUP/bash/feh.sh

# WSL 2
if grep -qEi "(Microsoft|WSL)" /proc/version &> /dev/null ; then
    # echo "Windows 10 Bash"
    export DISPLAY=$(grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'):0
fi

source $FAUTOSETUP/bash/aliases_x.sh
source $FAUTOSETUP/bash/aliases_serial.sh

# https://sourceforge.net/projects/vcxsrv/files/latest/download
# "C:\Program Files\VcXsrv\vcxsrv.exe" :0 -ac -terminate -lesspointer -multiwindow -clipboard -wgl -dpi auto
# netstat -abno|findstr 6000 (admin Powershell)
# Windows Defender Firewall with Advanced Security > Inbound Rules > New Rule > Program > %ProgramFiles%\VcXsrv\vcxsrv.exe
# if that works
# win+r shell:startup
# copy shortcut in there
#
# https://medium.com/javarevisited/using-wsl-2-with-x-server-linux-on-windows-a372263533c3
# https://www.shogan.co.uk/how-tos/wsl2-gui-x-server-using-vcxsrv/

# wms
if [ -f /bin/i3 ]; then
alias i3c="$EDITOR ~/.config/i3/config"
fi

if [ -f /bin/docker ]; then
  source $FAUTOSETUP/docker/aliases_docker.sh
fi

source $FAUTOSETUP/bash/aliases_sway.sh
# source $FAUTOSETUP/bash/aliases_regolith.sh

# ubuntu
# TODO check with lsb_release -i
source $FAUTOSETUP/bash/ubuntu_aliases.sh


